const scenarioSummaryData = {
  columns: [
    {
      key: 'scenarioName',
      title: 'Scenario Name',
    },
    {
      key: 'slPercent',
      title: 'SL %',
    },
    {
      key: 'revenueLoss',
      title: 'Revenue Loss',
    },
    {
      key: 'budgetUtilPercent',
      title: 'Budget Utilization %',
    },
    {
      key: 'doc',
      title: 'Document',
    },
    {
      key: 'fillRateIntegration',
      title: 'Fill Rate Integration',
    },
    {
      key: 'planningHorizon',
      title: 'Planning Horizon',
    },
    {
      key: 'createdDate',
      title: 'Created Date',
    },
    {
      key: 'createdBy',
      title: 'Created By',
    },
    {
      key: 'currentStatus',
      title: 'Status',
    },
    {
      key: 'remark',
      title: 'Remark',
    },
  ],
  dataSource: [
    {
      id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
      scenarioName: 'Scenario A',
      slPercent: 98.5,
      revenueLoss: '$120K',
      budgetUtilPercent: '82%',
      doc: 'DOC-23-A',
      fillRateIntegration: 'Yes',
      planningHorizon: '01 Jan 2025 - 30 Jun 2025',
      createdDate: '2025-04-01',
      createdBy: {
        name: 'John Doe',
        avatar: 'https://ui-avatars.com/api/?name=John+Doe&background=random',
      },
      currentStatus: {
        key: 'INPROGRESS',
        title: 'in progress',
      },
      remark: 'View Detail',
    },
    {
      id: 'a6b789e3-0cd8-4231-b16f-9fe0d40e1c87',
      scenarioName: 'Scenario B',
      slPercent: 95.0,
      revenueLoss: '$85K',
      budgetUtilPercent: '76%',
      doc: 'DOC-23-B',
      fillRateIntegration: 'No',
      planningHorizon: '01 Mar 2025 - 31 Aug 2025',
      createdDate: '2025-03-15',
      createdBy: {
        name: 'Priya Sharma',
        avatar: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=random',
      },
      currentStatus: {
        key: 'DONE',
        title: 'done',
      },
      remark: 'View Detail',
    },
    {
      id: 'bdc8c7ff-3b2e-4227-a8f9-3a5948b6b1a5',
      scenarioName: 'Scenario C',
      slPercent: 91.2,
      revenueLoss: '$150K',
      budgetUtilPercent: '68%',
      doc: 'DOC-23-C',
      fillRateIntegration: 'Yes',
      planningHorizon: '01 Feb 2025 - 31 Jul 2025',
      createdDate: '2025-02-20',
      createdBy: {
        name: 'Carlos Vega',
        avatar: 'https://ui-avatars.com/api/?name=Carlos+Vega&background=random',
      },
      currentStatus: {
        key: 'DONE',
        title: 'done',
      },
      remark: 'View Detail',
    },
    {
      id: 'dc1c6a2f-fc32-4d96-9d13-3dc84f8e6f97',
      scenarioName: 'Scenario D',
      slPercent: 88.3,
      revenueLoss: '$110K',
      budgetUtilPercent: '74%',
      doc: 'DOC-23-D',
      fillRateIntegration: 'No',
      planningHorizon: '01 Apr 2025 - 30 Sep 2025',
      createdDate: '2025-04-10',
      createdBy: {
        name: 'Meera Nair',
        avatar: 'https://ui-avatars.com/api/?name=Meera+Nair&background=random',
      },
      currentStatus: {
        key: 'DONE',
        title: 'done',
      },
      remark: 'View Detail',
    },
  ],
  total: 4,
}
const inventorySummaryData = {
  columns: [
    { key: 'division', title: 'Division' },
    { key: 'category', title: 'Category' },
    { key: 'segment', title: 'Segment' },
    { key: 'region', title: 'Region' },
    { key: 'city', title: 'City' },
    { key: 'locationType', title: 'Location Type' },
    { key: 'sourceWarehouseOrSupplier', title: 'Source (WH/Supplier)' },
    { key: 'location', title: 'Location' },
    { key: 'itemGP', title: 'Item GP' },
    { key: 'baseParameterCalculation', title: 'Base Parameter Calculation' },
    { key: 'leadTime', title: 'Lead Time' },
    { key: 'startDate', title: 'Start Date' },
    { key: 'endDate', title: 'End Date' },
  ],
  dataSource: [
    {
      key: '1',
      division: 'Healthcare',
      category: 'OTC Products',
      segment: 'Pharma',
      region: 'North',
      city: 'Delhi',
      locationType: 'Warehouse',
      sourceWarehouseOrSupplier: 'WH-001',
      location: 'WH-ND-01',
      itemGP: 'Item-001',
      baseParameterCalculation: 'System Generated',
      leadTime: '5 days',
      startDate: '2025-04-01',
      endDate: '2025-04-30',
    },
    {
      key: '2',
      division: 'Personal Care',
      category: 'Skin Care',
      segment: 'Retail',
      region: 'South',
      city: 'Bangalore',
      locationType: 'Store',
      sourceWarehouseOrSupplier: 'WH-002',
      location: 'STR-BLR-21',
      itemGP: 'Item-012',
      baseParameterCalculation: 'Manual Entry',
      leadTime: '7 days',
      startDate: '2025-04-05',
      endDate: '2025-05-05',
    },
    {
      key: '3',
      division: 'Household',
      category: 'Cleaning',
      segment: 'Modern Trade',
      region: 'West',
      city: 'Mumbai',
      locationType: 'Warehouse',
      sourceWarehouseOrSupplier: 'SUP-003',
      location: 'WH-MUM-03',
      itemGP: 'Item-024',
      baseParameterCalculation: 'Historical Avg',
      leadTime: '4 days',
      startDate: '2025-03-15',
      endDate: '2025-04-15',
    },
    {
      key: '4',
      division: 'Food',
      category: 'Snacks',
      segment: 'E-Commerce',
      region: 'East',
      city: 'Kolkata',
      locationType: 'Distribution Center',
      sourceWarehouseOrSupplier: 'DC-004',
      location: 'DC-KOL-09',
      itemGP: 'Item-037',
      baseParameterCalculation: 'System Generated',
      leadTime: '3 days',
      startDate: '2025-04-10',
      endDate: '2025-05-10',
    },
  ],
  total: 4,
}
const budgetOptimizationData = {
  columns: [
    { key: 'division', title: 'Division' },
    { key: 'category', title: 'Category' },
    { key: 'segment', title: 'Segment' },
    { key: 'region', title: 'Region' },
    { key: 'city', title: 'City' },
    { key: 'locationType', title: 'Location Type' },
    { key: 'sourceWarehouseOrSupplier', title: 'Source (WH/Supplier)' },
    { key: 'location', title: 'Location' },
    { key: 'itemGP', title: 'Item GP' },
    { key: 'prioritization', title: 'Prioritization' },
    { key: 'minTargetSL', title: 'Min Target SL' },
    { key: 'startDate', title: 'Start Date' },
    { key: 'endDate', title: 'End Date' },
  ],
  dataSource: [
    {
      key: '1',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'Fast',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'store',
      sourceWarehouseOrSupplier: 'WH-001',
      location: 'WH-ND-01',
      itemGP: 'All',
      prioritization: 'Budget',
      minTargetSL: '95%',
      startDate: '2025-04-01',
      endDate: '2025-04-30',
    },
    {
      key: '2',
      division: 'Personal Care',
      category: 'Hair Care',
      segment: 'Retail',
      region: 'South',
      city: 'Chennai',
      locationType: 'Store',
      sourceWarehouseOrSupplier: 'SUP-002',
      location: 'STR-CHN-05',
      itemGP: 'Item-015',
      prioritization: 'Medium',
      minTargetSL: '90%',
      startDate: '2025-04-05',
      endDate: '2025-05-05',
    },
    {
      key: '3',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'slow',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'store',
      sourceWarehouseOrSupplier: 'DC-003',
      location: 'DC-MUM-02',
      itemGP: 'All',
      prioritization: 'Budget',
      minTargetSL: '85%',
      startDate: '2025-03-20',
      endDate: '2025-04-20',
    },
    {
      key: '4',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'Modern Trade',
      region: 'Fast',
      city: 'Amulj',
      locationType: 'store',
      sourceWarehouseOrSupplier: 'WH-004',
      location: 'WH-KOL-07',
      itemGP: 'All',
      prioritization: 'Budget',
      minTargetSL: '98%',
      startDate: '2025-04-10',
      endDate: '2025-05-10',
    },
  ],
  total: 4,
}
const replenishmentRecommendation = {
  columns: [
    { key: 'division', title: 'Division' },
    { key: 'category', title: 'Category' },
    { key: 'segment', title: 'Segment' },
    { key: 'region', title: 'Region' },
    { key: 'city', title: 'City' },
    { key: 'locationType', title: 'Location Type' },
    { key: 'sourceWarehouseOrSupplier', title: 'Source (WH/Supplier)' },
    { key: 'location', title: 'Location' },
    { key: 'itemGP', title: 'Item GP' },
    { key: 'inventoryPolicy', title: 'Inventory Policy' },
    { key: 'safetyStock', title: 'Safety Stock' },
    { key: 'qrQ1', title: 'QR Q1' },
    { key: 'qrQ2', title: 'QR Q2' },
    { key: 'tsT', title: 'TS T' },
    { key: 'sSs', title: 'SSS' },
  ],
  dataSource: [
    {
      key: '1',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'slow',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'Warehouse',
      sourceWarehouseOrSupplier: 'WH-001',
      location: 'WH-ND-01',
      itemGP: 'Item-001',
      inventoryPolicy: 'QR',
      safetyStock: 150,
      qrQ1: 50,
      qrQ2: 60,
      tsT: 5,
      sSs: 30,
    },
    {
      key: '2',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'slow',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'Store',
      sourceWarehouseOrSupplier: 'SUP-002',
      location: 'STR-BLR-02',
      itemGP: 'Item-007',
      inventoryPolicy: 'QR',
      safetyStock: 100,
      qrQ1: 40,
      qrQ2: 55,
      tsT: 3,
      sSs: 25,
    },
    {
      key: '3',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'Fast',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'Distribution Center',
      sourceWarehouseOrSupplier: 'DC-003',
      location: 'DC-MUM-04',
      itemGP: 'Item-019',
      inventoryPolicy: 'QR',
      safetyStock: 80,
      qrQ1: 30,
      qrQ2: 35,
      tsT: 2,
      sSs: 20,
    },
    {
      key: '4',
      division: 'Beauty',
      category: 'Dermo Skin Care',
      segment: 'All',
      region: 'Madinah',
      city: 'Amulj',
      locationType: 'Warehouse',
      sourceWarehouseOrSupplier: 'WH-004',
      location: 'WH-KOL-06',
      itemGP: 'Item-025',
      inventoryPolicy: 'QR',
      safetyStock: 120,
      qrQ1: 45,
      qrQ2: 50,
      tsT: 4,
      sSs: 28,
    },
  ],
  total: 4,
}

const supplierFillData = {
  columns: [
    { key: 'division', title: 'Division' },
    { key: 'category', title: 'Category' },
    { key: 'segment', title: 'Segment' },
    { key: 'region', title: 'Region' },
    { key: 'city', title: 'City' },
    { key: 'location', title: 'Location' },
    { key: 'supplierSite', title: 'Supplier Site' },
    { key: 'fillRate', title: 'Fill Rate' },
    { key: 'startDate', title: 'Start Date' },
    { key: 'endDate', title: 'End Date' },
  ],
  dataSource: [
    {
      key: '1',
      division: 'Healthcare',
      category: 'Medicines',
      segment: 'Pharma',
      region: 'North',
      city: 'Delhi',
      location: 'WH-ND-01',
      supplierSite: 'SUP-DEL-001',
      fillRate: '95%',
      startDate: '2025-01-01',
      endDate: '2025-06-30',
    },
    {
      key: '2',
      division: 'Personal Care',
      category: 'Hair Care',
      segment: 'Retail',
      region: 'West',
      city: 'Mumbai',
      location: 'STR-MUM-03',
      supplierSite: 'SUP-MUM-007',
      fillRate: '90%',
      startDate: '2025-02-15',
      endDate: '2025-07-31',
    },
    {
      key: '3',
      division: 'Food',
      category: 'Dry Food',
      segment: 'E-Commerce',
      region: 'South',
      city: 'Bangalore',
      location: 'DC-BLR-05',
      supplierSite: 'SUP-BLR-002',
      fillRate: '87%',
      startDate: '2025-03-10',
      endDate: '2025-08-30',
    },
    {
      key: '4',
      division: 'Household',
      category: 'Detergents',
      segment: 'Modern Trade',
      region: 'East',
      city: 'Kolkata',
      location: 'WH-KOL-04',
      supplierSite: 'SUP-KOL-008',
      fillRate: '92%',
      startDate: '2025-01-20',
      endDate: '2025-06-15',
    },
  ],
  total: 4,
}

const optimalReplenishment = {
  columns: [
    { key: 'division', title: 'Division' },
    { key: 'category', title: 'Category' },
    { key: 'segment', title: 'Segment' },
    { key: 'region', title: 'Region' },
    { key: 'city', title: 'City' },
    { key: 'locationType', title: 'Location Type' },
    { key: 'sourceWarehouseOrSupplierSite', title: 'Source (Warehouse/Supplier Site)' },
    { key: 'location', title: 'Location' },
    { key: 'itemGP', title: 'Item GP' },
    { key: 'replenishmentFrequency', title: 'Replenishment Frequency' },
    { key: 'leadTime', title: 'Lead Time' },
    { key: 'startDate', title: 'Start Date' },
    { key: 'endDate', title: 'End Date' },
  ],
  dataSource: [
    {
      key: '1',
      division: 'Healthcare',
      category: 'OTC Drugs',
      segment: 'Pharma',
      region: 'North',
      city: 'Delhi',
      locationType: 'Warehouse',
      sourceWarehouseOrSupplierSite: 'SUP-DEL-003',
      location: 'WH-DEL-001',
      itemGP: 'ITEM-GP-1001',
      replenishmentFrequency: 2,
      leadTime: '5',
      startDate: '2025-01-01',
      endDate: '2025-06-30',
    },
    {
      key: '2',
      division: 'Personal Care',
      category: 'Skin Care',
      segment: 'Retail',
      region: 'West',
      city: 'Mumbai',
      locationType: 'Store',
      sourceWarehouseOrSupplierSite: 'SUP-MUM-005',
      location: 'STR-MUM-010',
      itemGP: 'ITEM-GP-2023',
      replenishmentFrequency: 2,
      leadTime: '7',
      startDate: '2025-02-15',
      endDate: '2025-07-31',
    },
    {
      key: '3',
      division: 'Food',
      category: 'Snacks',
      segment: 'E-Commerce',
      region: 'South',
      city: 'Bangalore',
      locationType: 'Distribution Center',
      sourceWarehouseOrSupplierSite: 'WH-BLR-002',
      location: 'DC-BLR-004',
      itemGP: 'ITEM-GP-3309',
      replenishmentFrequency: 2,
      leadTime: '3',
      startDate: '2025-03-10',
      endDate: '2025-08-30',
    },
    {
      key: '4',
      division: 'Household',
      category: 'Cleaning',
      segment: 'Modern Trade',
      region: 'East',
      city: 'Kolkata',
      locationType: 'Retail Outlet',
      sourceWarehouseOrSupplierSite: 'SUP-KOL-009',
      location: 'STR-KOL-006',
      itemGP: 'ITEM-GP-4110',
      replenishmentFrequency: 1,
      leadTime: '6',
      startDate: '2025-01-20',
      endDate: '2025-06-15',
    },
  ],
  total: 4,
}

const viewDetailsData = {
  columns: [
    {
      key: 'key',
      title: 'Key',
    },
    {
      key: 'locationTypee',
      title: 'Location Type',
    },
    {
      key: 'locationNamee',
      title: 'Location Name',
    },
    {
      key: 'categorye',
      title: 'Category',
    },
    {
      key: 'segmente',
      title: 'Segment',
    },
    {
      key: 'regione',
      title: 'Region',
    },
    {
      key: 'sourceWarehouseOrSupplierSitee',
      title: 'Source Warehouse or Supplier Site',
    },
    {
      key: 'citye',
      title: 'City',
    },
    {
      key: 'slPercent',
      title: 'Service Level (%)',
    },
    {
      key: 'revenueLoss',
      title: 'Revenue Loss',
    },
    {
      key: 'budgetUtilised',
      title: 'Budget Utilised (%)',
    },
    {
      key: 'doc',
      title: 'Days of Coverage (DoC)',
    },
    {
      key: 'noOrdersRecommended',
      title: 'Number of Orders Recommended',
    },
    {
      key: 'mdqDos',
      title: 'MDQ Days of Supply',
    },
    {
      key: 'avgInvDocRsp',
      title: 'Avg Inventory DoC at Response',
    },
    {
      key: 'startInvDocRsp',
      title: 'Start Inventory DoC at Response',
    },
    {
      key: 'overMdqDos',
      title: 'Over MDQ Days of Supply',
    },
    {
      key: 'addedDos',
      title: 'Added Days of Supply',
    },
  ],

  dataSource: [
    {
      key: '1',
      locationTypee: 'DC',
      locationNamee: 'DC-001',
      categorye: 'Dermo Skin Care',
      segmente: '1a_ExtremeFast',
      regione: 'North',
      sourceWarehouseOrSupplierSitee: 'SUP-DEL-003',
      citye: 'Delhi',
      slPercent: '98%',
      revenueLoss: '$12,000',
      budgetUtilised: '85%',
      doc: '35',
      noOrdersRecommended: 12,
      mdqDos: '15',
      avgInvDocRsp: '13',
      startInvDocRsp: '10',
      overMdqDos: '2',
      addedDos: '1',
    },
    {
      key: '2',
      locationTypee: 'DC',
      locationNamee: 'DC-002',
      categorye: 'Skin Care',
      segmente: '1a_ExtremeFast',
      regione: 'West',
      sourceWarehouseOrSupplierSitee: 'SUP-MUM-005',
      citye: 'Mumbai',
      slPercent: '95%',
      revenueLoss: '$8,500',
      budgetUtilised: '78%',
      doc: '28',
      noOrdersRecommended: 9,
      mdqDos: '10',
      avgInvDocRsp: '9',
      startInvDocRsp: '7',
      overMdqDos: '1',
      addedDos: '2',
    },
    {
      key: '3',
      locationTypee: 'DC',
      locationNamee: 'DC-003',
      categorye: 'Snacks',
      segmente: '1a_ExtremeFast',
      regione: 'South',
      sourceWarehouseOrSupplierSitee: 'WH-BLR-002',
      citye: 'Bangalore',
      slPercent: '92%',
      revenueLoss: '$15,200',
      budgetUtilised: '90%',
      doc: '40',
      noOrdersRecommended: 15,
      mdqDos: '18',
      avgInvDocRsp: '16',
      startInvDocRsp: '12',
      overMdqDos: '3',
      addedDos: '1',
    },
    {
      keye: '4',
      locationTypee: 'DC',
      locationNamee: 'DC-004',
      categorye: 'Cleaning',
      segmente: '1a_ExtremeFast',
      regione: 'East',
      sourceWarehouseOrSupplierSitee: 'SUP-KOL-009',
      citye: 'Kolkata',
      slPercent: '89%',
      revenueLoss: '$6,750',
      budgetUtilised: '72%',
      doc: '25',
      noOrdersRecommended: 7,
      mdqDos: '9',
      avgInvDocRsp: '8',
      startInvDocRsp: '6',
      overMdqDos: '1',
      addedDos: '1',
    },
  ],

  total: 4
}

export const parametersData = {
  'inventory-policy-simulation-engine': inventorySummaryData,
  'budget-optimization': budgetOptimizationData,
  'replenishment-recommendations': replenishmentRecommendation,
  'supplier-fill-rate-parameter-update': supplierFillData,
  'optimal-replenishment-frequency': optimalReplenishment,
  'scenario-summary': scenarioSummaryData,
  'view-details': viewDetailsData,
}
